name: fechy-os
description: Fedora Sway Atomic with CachyOS kernel, Nvidia and Hyprland.
base-image: ghcr.io/ublue-os/base-main
image-version: 42

modules:
  - type: script
    scripts:
      - change-kernel.sh
      - build-nvidia.sh

  - type: rpm-ostree
    repos:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm
    install:
      #codecs
      - ffmpeg
      - gstreamer1-plugin-libav
      - gstreamer1-vaapi
      # hyprland
      - hyprland
      - xdg-desktop-portal-hyprland
      - waybar
      - rofi-wayland
      - dunst
      - swaybg
      - wlogout
      - grim
      - slurp
      - wl-clipboard
      - kitty
      # sys integration
      - lxpolkit
      - qt5-qtwayland
      - qt6-qtwayland
      - network-manager-applet
      - pavucontrol
      - blueman
      - brightnessctl
      # sys utils
      - distrobox
      - fastfetch
      - btop

  - type: files
    files:
      - source: system
        destination: /
  
  - type: systemd
    system:
      enabled:
        - cachyos-selinux-fix.service
        - nvidia-hibernate.service
        - nvidia-suspend.service
        - nvidia-resume.service

  - type: signing